version: '3'
services:
  eureka-server:
    image: eureka-server
    ports:
     - "8761:8761"
  zuul-server:
    image: zuul-server
    depends_on:
    - eureka-server
    ports:
     - "8765:8765"
     - "9090:9090"
  meeting:
    image: meeting
    depends_on:
     - eureka-server
     - zuul-server
    ports:
     - "4349:4349"