info:
  component: Zuul Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  routes:
    meeting:
      path: /meeting/**
      url: http://localhost:4349
    user:
      path: /user/**
      url: http://localhost:4359

server:
  port: 9090

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: zuul-server
  cloud:
    config:
      enabled: false
