info:
  component: Zuul Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  routes:
    meeting:
      path: /meeting/**
      url: http://meeting:4349

server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: zuul-server